#!/bin/bash
 
git diff --cached --name-status --diff-filter=ACMR | while read STATUS FILE; do
if [[ "$FILE" =~ ^.+(php|inc)$ ]]; then
    php -l "$FILE"
    if [ $? -ne 0 ]; then
        echo "Aborting commit due to files with syntax errors" >&2
        exit 1
    fi
elif [[ "$FILE" =~ ^.+(twig)$ ]]; then
    twig-lint lint "$FILE"
    if [ $? -ne 0 ]; then
        echo "Aborting commit due to files with syntax errors" >&2
        exit 1
    fi
elif [[ "$FILE" =~ ^.+(yml)$ ]]; then
    ruby -e "require 'yaml'; YAML.load_file('$FILE')"
    if [ $? -ne 0 ]; then
        echo "Aborting commit due to files with syntax errors" >&2
        exit 1
    fi
elif [[ "$FILE" =~ ^.+(css)$ ]]; then
    csslint --quiet $FILE
    if [ $? -ne 0 ]; then
        echo "Aborting commit due to files with syntax errors" >&2
        exit 1
    fi
fi
done
