#!/bin/sh
 
BRANCH_NAME=$(git symbolic-ref --short HEAD  | sed s,feature/,,)
if [ -n "$BRANCH_NAME" ] && [ "$BRANCH_NAME" != "master" ] && [ "$BRANCH_NAME" != "develop" ] && [ "$BRANCH_NAME" != "Remote_Develop" ]; then
	sed -i.bak -e "1s@^@[$BRANCH_NAME] @" $1
fi
